### ISSUE TITLE
Cannot deploy this on NuxtHub

### ISSUE THREAD

**Issue by fayazara** [RihanArfan/chat-with-pdf#2]
hey @RihanArfan this template just throws a error 500 when i try to clone (no changes) and then deplot it in NuxtHub 

I just picked the template - imported the repo on NuxtHub admin and the deployment fails - am I missing something?

 
<img width="1190" alt="image" src="https://github.com/user-attachments/assets/8bc28fe5-dd12-4bf4-8155-35a687158e82">

**Comment by RihanArfan** [comment]
Hello :) I've successfully deployed it, so I think it was a one-off issue with CI. If you retry the deployment, it should work.

I've also updated the dependencies now, so as you've made no changes I suggest recreating the repo again because migrations are now automatically applied.

[![Deploy to NuxtHub](https://hub.nuxt.com/button.svg)](https://hub.nuxt.com/new?template=chat-with-pdf)

Let me know if the issue persists.
